twig:
    file_name_pattern: '*.twig'
    globals:
        main_nav:
            - label: home
              route: /
            - label: about
              route: '/about'
            - label: actions
              route: '/actions'
            - label: writings
              route: '/writings'
            - label: Q & A
              route: '/questions'
              template: questions
            - label: join
              route: '/join'
            - label: resources
              route: '/resources'

when@test:
    twig:
        strict_variables: true

